version: '3.5'

services:
    php:
        container_name: php
        build:
            context: .
        volumes:
            - ./:/var/www/html
        ports:
            - "8000:80"
        networks:
            - app

    webserver:
        container_name: webserver
        image: nginx:stable-alpine3.17
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "80:80"
        networks:
            - app
        depends_on:
            - php

networks:
    app:
